### ISSUE TITLE
How to get rid off smooth scroll effect?

### ISSUE THREAD

**Issue by iskotar** [brianmcallister/react-auto-scroll#9]

**Comment by brianmcallister** [comment]
Hey @iskotar, great question! Although there's no option to do that via React props, you can accomplish this effect with the following snippet of CSS:

```css
.react-auto-scroll__scroll-container {
  scroll-behavior: auto;
}
```

If you think it would be useful, I can add a prop to the component to set this via JavaScript. How does something like this look?

```ts
<AutoScroll scrollBehavior="auto" />
```
